# Generated by Django 4.2 on 2023-06-02 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصنيف',
            },
        ),
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المتبرع')),
            ],
            options={
                'verbose_name': 'متبرع',
                'verbose_name_plural': 'المتبرع',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='سبب الاعانة')),
            ],
            options={
                'verbose_name': 'سبب اعانة',
                'verbose_name_plural': 'اسباب الاعانات',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العنصر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'عنصر تبرع',
                'verbose_name_plural': 'عناصر تبرع',
            },
        ),
        migrations.CreateModel(
            name='InOutCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name=' الكمية')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=' التاريخ')),
                ('file', models.FileField(blank=True, null=True, upload_to='inbound_files/', verbose_name=' ملفات توثيق الورود')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.item', verbose_name=' العنصر')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الحالة')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name=' ملاحظات')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name=' تاريخ الاضافة')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.status', verbose_name='سبب الاعانة')),
            ],
            options={
                'verbose_name': 'حالة',
                'verbose_name_plural': 'الحالات',
            },
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField(default=0, verbose_name=' الكمية المتاحة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.item', verbose_name=' العنصر')),
            ],
            options={
                'verbose_name': 'كمية متاحة',
                'verbose_name_plural': 'كميات العناصر المتاحة',
            },
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('inoutcommon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zakah.inoutcommon')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.case', verbose_name=' الحالة الصادر لها')),
            ],
            options={
                'verbose_name': 'صادر',
                'verbose_name_plural': 'الصادر',
            },
            bases=('zakah.inoutcommon',),
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('inoutcommon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zakah.inoutcommon')),
                ('donator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.donator', verbose_name=' المتبرع')),
            ],
            options={
                'verbose_name': 'الوارد',
                'verbose_name_plural': 'الوارد',
            },
            bases=('zakah.inoutcommon',),
        ),
    ]
