# Generated by Django 4.2 on 2023-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=70, verbose_name='اسم المدير')),
                ('manager_phone', models.CharField(max_length=15, verbose_name='تليفون المدير')),
                ('manager_mail', models.CharField(max_length=30, verbose_name='ايميل المدير')),
                ('manager_address', models.CharField(max_length=70, verbose_name='تليفون المدير')),
                ('manager_title', models.CharField(max_length=70, verbose_name=' عنوان الموقع')),
                ('manager_caption1', models.CharField(max_length=200, verbose_name='كلمة معبرة اولى ')),
                ('manager_caption2', models.CharField(max_length=300, verbose_name='كلمة معبرة ثانية ')),
            ],
            options={
                'verbose_name': 'معلومة الصفحة الرئيسية',
                'verbose_name_plural': 'معلومات الصفحة الرئيسية',
            },
        ),
    ]
