# Generated by Django 4.2 on 2023-07-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name=' محل التخزين')),
            ],
            options={
                'verbose_name': 'مكان تخزين',
                'verbose_name_plural': 'اماكن التخزين',
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='manager_address',
            field=models.CharField(max_length=70, verbose_name='عنوان المدير'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.place', verbose_name=' مكان التخزين'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.place', verbose_name=' مكان التخزين'),
        ),
    ]
