# Generated by Django 4.2 on 2023-07-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0003_place_alter_home_manager_address_inbound_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caselevel', models.CharField(max_length=50, verbose_name='درجة الحالة')),
            ],
            options={
                'verbose_name': ' درجة حالة',
                'verbose_name_plural': ' درجة الحالة',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='caselevel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zakah.caselevel', verbose_name='درجة الحالة'),
            preserve_default=False,
        ),
    ]
