# Generated by Django 4.1.3 on 2023-05-10 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0003_alter_inbound_date_alter_inbound_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
