# Generated by Django 4.1.3 on 2023-05-10 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0004_alter_inbound_date_alter_outbound_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
