# Generated by Django 4.2 on 2023-07-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0004_caselevel_case_caselevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caselevel',
            field=models.ForeignKey(default='مؤقته', on_delete=django.db.models.deletion.CASCADE, to='zakah.caselevel', verbose_name='درجة الحالة'),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount_money', models.IntegerField(default=0, verbose_name='  صرفية مالية')),
                ('caselevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.caselevel', verbose_name='درجة الحالة')),
            ],
            options={
                'verbose_name': 'شهرية مالية',
                'verbose_name_plural': 'شهريات مالية',
            },
        ),
    ]
