# Generated by Django 4.1.3 on 2023-07-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0005_alter_case_caselevel_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.case', verbose_name=' الحالة')),
            ],
            options={
                'verbose_name': 'شهرية',
                'verbose_name_plural': 'متابعة الشهريات',
            },
        ),
    ]
