# Generated by Django 4.1.3 on 2023-05-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0005_alter_inbound_date_alter_outbound_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inbound',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='inbound_files/'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='outbound_files/'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.donator'),
        ),
    ]
