# Generated by Django 4.1.3 on 2023-07-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0006_distributionwatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateTimeField(auto_now=True, verbose_name=' تاريخ الشهرية')),
                ('file', models.FileField(blank=True, null=True, upload_to='month_pay_files/', verbose_name=' ملفات توثيق الورود')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.case', verbose_name=' الحالة')),
            ],
            options={
                'verbose_name': 'شهرية',
                'verbose_name_plural': 'الشهريات',
            },
        ),
    ]
