# Generated by Django 4.1.3 on 2023-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0007_status_case_outbound_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'عنصر', 'verbose_name_plural': 'العناصر'},
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم النصر'),
        ),
    ]
