# Generated by Django 4.1.3 on 2023-05-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0009_mymodel_alter_item_options_alter_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
