# Generated by Django 4.1.3 on 2023-05-27 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0010_delete_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='file',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='date',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='file',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='id',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='item',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='quantity',
        ),
        migrations.CreateModel(
            name='InOutCommon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='inoutbound_files/')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakah.item')),
            ],
        ),
        migrations.AddField(
            model_name='inbound',
            name='inoutcommon_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zakah.inoutcommon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbound',
            name='inoutcommon_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zakah.inoutcommon'),
            preserve_default=False,
        ),
    ]
