# Generated by Django 4.1.3 on 2023-05-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0011_remove_inbound_date_remove_inbound_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصنيف',
            },
        ),
        migrations.AddField(
            model_name='inoutcommon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zakah.category'),
        ),
    ]
